"""Create tables owners, pets


Revision ID: 87718fc2c074
Revises: 
Create Date: 2024-01-09 14:49:07.693722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87718fc2c074'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
